<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<DisableDiagnosticTracing>true</DisableDiagnosticTracing>
		
		<MinVerTagPrefix>v</MinVerTagPrefix>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MinVer" Version="6.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<!-- Used for rendering -->
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
		<PackageReference Include="SixLabors.Fonts" Version="2.0.3" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.2" />
		<!-- Used by format parsers -->
		<PackageReference Include="PeNet" Version="4.1.1" />
		<!-- <PackageReference Include="DiscUtils" Version="0.16.13" /> -->
		<!-- Used by SdlExportHandler -->
		<PackageReference Include="SDL-Sharp" Version="2.2.5" />
		<!-- Used by FfmpegExportHandler -->
		<PackageReference Include="FFmpeg.AutoGen" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="libs\" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="SDL2.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
